logging:
  level:
    root: 'OFF'
spring:
  data:
    redis:
      client-type: jedis
      database: 0
      host: ${redis_host}
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
    password: root
    url: jdbc:mysql://${dbhost}:3306/bookking
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: false
  profiles:
    active: ${active}
  thymeleaf:
    enabled: false

